#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QOpenGLWindow>

class View;

namespace Ui {
class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QOpenGLWindow {
   Q_OBJECT
public:
   MainWindow(QWidget *parent = 0);
   ~MainWindow();

private:
   // Auto-generated by Qt. DO NOT RENAME!
   Ui::MainWindow *ui;
};

#endif // MAINWINDOW_H
