#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>

#include <QButtonGroup>
#include <QMainWindow>

class Canvas3D;

namespace Ui {
class MainWindow;
}

class DataBinding;

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
   Q_OBJECT
public:
   MainWindow(QWidget *parent = 0);
   ~MainWindow();

protected:

   // Overridden from QWidget. Handles the window resize event.
   virtual void changeEvent(QEvent *e);

   // Overridden from QWidget. Handles the window close event.
   virtual void closeEvent(QCloseEvent *e);


private:

   // Sets up the data bindings between the UI and app settings
   void dataBind();

   Canvas3D *m_canvas3D;

   // EXCEPTION: 'ui' member which is auto-generated by Qt. DO NOT RENAME!
   Ui::MainWindow *ui;

public slots:

   // Used internally to keep data bindings and the user interface in sync.
   void settingsChanged();


   void renderImage();
};

#endif // MAINWINDOW_H
